{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cookieingress.serviceAccountName" . }}
  labels:
{{ include "cookieingress.labels" . | nindent 4 }}
{{- end -}}
